### ISSUE TITLE
Bug in PHP 5.4

### ISSUE THREAD

**Issue by lindseydiloreto** [nilsenpaul/npeditmultipleelements#1]
This isn't working for me in PHP 5.4...

>Fatal error: Can't use method return value in write context in /npeditmultipleelements/services/NpEditMultipleElementsService.php on line 34

If I switch to a higher version of PHP, it works fine.

**Comment by lindseydiloreto** [comment]
Cool plugin, btw! :smile:

**Comment by nilsenpaul** [comment]
Fixed with #3. Never noticed this issue, must've missed it somewhere, sorry! Thanks for the feedback!

**Comment by lindseydiloreto** [comment]
Ha, better late than never! 😉
