### ISSUE TITLE
Craft 2 version logs me out after edits.

### ISSUE THREAD

**Issue by TomDeSmet** [nilsenpaul/npeditmultipleelements#5]
Whenever I edited the entries I selected, Craft logs me out after the last save and sends me back to the login page.

**Comment by nilsenpaul** [comment]
Tom, that's strange. Is there anything in the logs that could help clarify what happens?

**Comment by nilsenpaul** [comment]
Tom, I encountered this on an old Craft 2 site too. Seems that `craft()->session->destroy`, used to clear certain sessions, clears ALL session now. It's fixed. Thanks for mentioning this!
